# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node LTS on Alpine for lightweight image
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts
RUN npm run build

# Production image
FROM node:lts-alpine AS runtime
WORKDIR /app
# Copy built files and production dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
# Install only production dependencies
RUN npm ci --only=production --ignore-scripts

# Default command
CMD ["node","build/index.js"]
